package recognitioncommons.models.country

object CountryFlagEmojis {
    val emojiUnicodeToCountry = mapOf(
        "\uD83C\uDDED\uD83C\uDDF0" to Country.HONG_KONG,
        "\uD83C\uDDEF\uD83C\uDDF5" to Country.JAPAN,
        "\uD83C\uDDFA\uD83C\uDDF8" to Country.USA,
        "\uD83C\uDDF0\uD83C\uDDF7" to Country.SOUTH_KOREA,
        "\uD83C\uDDEA\uD83C\uDDFA" to Country.EUROPE,
        "\uD83C\uDDF8\uD83C\uDDEC" to Country.SINGAPORE,
        "\uD83C\uDDEE\uD83C\uDDF3" to Country.INDIA,
        "\uD83C\uDDE8\uD83C\uDDF3" to Country.CHINA,
        "\uD83C\uDDE6\uD83C\uDDEA" to Country.UAE,
        "\uD83C\uDDF7\uD83C\uDDFA" to Country.RUSSIA,
        "\uD83C\uDDE6\uD83C\uDDFA" to Country.AUSTRALIA,
        "\uD83C\uDDF0\uD83C\uDDFF" to Country.KAZAKHSTAN,
        "\uD83C\uDDE8\uD83C\uDDE6" to Country.CANADA,
        "\uD83C\uDDFB\uD83C\uDDF3" to Country.VIETNAM,
        "\uD83C\uDDEC\uD83C\uDDE7" to Country.UNITED_KINGDOM,
        "\uD83C\uDDF9\uD83C\uDDED" to Country.THAILAND,
        "\uD83C\uDDF2\uD83C\uDDFD" to Country.MEXICO,
        "\uD83C\uDDE7\uD83C\uDDF7" to Country.BRAZIL,
        "\uD83C\uDDF2\uD83C\uDDF4" to Country.MACAU,
        "\uD83C\uDDF5\uD83C\uDDFE" to Country.PARAGUAY,
        "\uD83C\uDDF8\uD83C\uDDE6" to Country.SAUDI_ARABIA,
        "\uD83C\uDDF3\uD83C\uDDFF" to Country.NEW_ZEALAND,
        "\uD83C\uDDFA\uD83C\uDDE6" to Country.UKRAINE,
        "\uD83C\uDDF0\uD83C\uDDEC" to Country.KYRGYZ_REPUBLIC,
        "\uD83C\uDDF9\uD83C\uDDEF" to Country.TAJIKISTAN,
        "\uD83C\uDDF9\uD83C\uDDF2" to Country.TURKMENISTAN,
        "\uD83C\uDDFA\uD83C\uDDFF" to Country.UZBEKISTAN,
        "\uD83C\uDDEC\uD83C\uDDEA" to Country.GEORGIA,
    )

    val countryToEmojiUnicode = mapOf(
        Country.HONG_KONG to "\uD83C\uDDED\uD83C\uDDF0",
        Country.JAPAN to "\uD83C\uDDEF\uD83C\uDDF5",
        Country.USA to "\uD83C\uDDFA\uD83C\uDDF8",
        Country.SOUTH_KOREA to "\uD83C\uDDF0\uD83C\uDDF7",
        Country.EUROPE to "\uD83C\uDDEA\uD83C\uDDFA",
        Country.SINGAPORE to "\uD83C\uDDF8\uD83C\uDDEC",
        Country.INDIA to "\uD83C\uDDEE\uD83C\uDDF3",
        Country.CHINA to "\uD83C\uDDE8\uD83C\uDDF3",
        Country.UAE to "\uD83C\uDDE6\uD83C\uDDEA",
        Country.RUSSIA to "\uD83C\uDDF7\uD83C\uDDFA",
        Country.AUSTRALIA to "\uD83C\uDDE6\uD83C\uDDFA",
        Country.KAZAKHSTAN to "\uD83C\uDDF0\uD83C\uDDFF",
        Country.CANADA to "\uD83C\uDDE8\uD83C\uDDE6",
        Country.VIETNAM to "\uD83C\uDDFB\uD83C\uDDF3",
        Country.UNITED_KINGDOM to "\uD83C\uDDEC\uD83C\uDDE7",
        Country.THAILAND to "\uD83C\uDDF9\uD83C\uDDED",
        Country.MEXICO to "\uD83C\uDDF2\uD83C\uDDFD",
        Country.BRAZIL to "\uD83C\uDDE7\uD83C\uDDF7",
        Country.MACAU to "\uD83C\uDDF2\uD83C\uDDF4",
        Country.PARAGUAY to "\uD83C\uDDF5\uD83C\uDDFE",
        Country.SAUDI_ARABIA to "\uD83C\uDDF8\uD83C\uDDE6",
        Country.NEW_ZEALAND to "\uD83C\uDDF3\uD83C\uDDFF",
        Country.UKRAINE to "\uD83C\uDDFA\uD83C\uDDE6",
        Country.KYRGYZ_REPUBLIC to "\uD83C\uDDF0\uD83C\uDDEC",
        Country.TAJIKISTAN to "\uD83C\uDDF9\uD83C\uDDEF",
        Country.TURKMENISTAN to "\uD83C\uDDF9\uD83C\uDDF2",
        Country.UZBEKISTAN to "\uD83C\uDDFA\uD83C\uDDFF",
        Country.GEORGIA to "\uD83C\uDDEC\uD83C\uDDEA",
    )
}
